/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_DICT_FOR_PAGE = 'DICT/FINDFORPAGE';
export const FIND_DICT_FOR_PAGE_FETCH = 'DICT/FINDFORPAGEFETCH';
export const FIND_DICT_FOR_PAGE_SUCCESS = 'DICT/FINDFORPAGESUCCESS';
export const FIND_DICT_FOR_PAGE_ERROR = 'DICT/FINDFORPAGEERROR';
