export const FIND_MUSIC_FOR_PAGE = 'MUSIC/FINDFORPAGE';
export const FIND_MUSIC_FOR_PAGE_FETCH = 'MUSIC/FINDFORPAGEFETCH';
export const FIND_MUSIC_FOR_PAGE_SUCCESS = 'MUSIC/FINDFORPAGESUCCESS';
export const FIND_MUSIC_FOR_PAGE_ERROR = 'MUSIC/FINDFORPAGEERROR';
