/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_DICTTYPE_FOR_PAGE = 'DICTTYPE/FINDFORPAGE';
export const FIND_DICTTYPE_FOR_PAGE_FETCH = 'DICTTYPE/FINDFORPAGEFETCH';
export const FIND_DICTTYPE_FOR_PAGE_SUCCESS = 'DICTTYPE/FINDFORPAGESUCCESS';
export const FIND_DICTTYPE_FOR_PAGE_ERROR = 'DICTTYPE/FINDFORPAGEERROR';
