/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_DEPARTMENT = 'UNIFYDEPARTMENT/CHANGEID';
export const CHANGE_ACTIVE_FOR_UNIFY_DEPARTMENT = 'UNIFYDEPARTMENT/CHANGEACTIVE';
export const FIND_BY_ID_FOR_UNIFY_DEPARTMENT = 'UNIFYDEPARTMENT/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_DEPARTMENT_FETCH = 'UNIFYDEPARTMENT/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_DEPARTMENT_SUCCESS = 'UNIFYDEPARTMENT/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_DEPARTMENT_ERROR = 'UNIFYDEPARTMENT/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_DEPARTMENT = 'UNIFYDEPARTMENT/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_DEPARTMENT = 'UNIFYDEPARTMENT/UPDATE';
export const UPDATE_FOR_UNIFY_DEPARTMENT_FETCH = 'UNIFYDEPARTMENT/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_DEPARTMENT_SUCCESS = 'UNIFYDEPARTMENT/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_DEPARTMENT_ERROR = 'UNIFYDEPARTMENT/UPDATEERROR';
