/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_DEPARTMENT_FOR_PAGE = 'DEPARTMENT/FINDFORPAGE';
export const FIND_DEPARTMENT_FOR_PAGE_FETCH = 'DEPARTMENT/FINDFORPAGEFETCH';
export const FIND_DEPARTMENT_FOR_PAGE_SUCCESS = 'DEPARTMENT/FINDFORPAGESUCCESS';
export const FIND_DEPARTMENT_FOR_PAGE_ERROR = 'DEPARTMENT/FINDFORPAGEERROR';
